### ISSUE TITLE
redmine:plugins:migrate fails

### ISSUE THREAD

**Issue by prodigy7** [centosadmin/redmine_telegram_common#27]
I try to install this plugin but it fails. 

```
root@b77ab14ea147:/home/redmine/redmine/plugins# bundle exec rake redmine:plugins:migrate NAME=redmine_telegram_common VERSION=0
(in /home/redmine/redmine)
Migrating redmine_telegram_common (Redmine Telegram Common plugin)...
root@b77ab14ea147:/home/redmine/redmine/plugins# bundle exec rake redmine:plugins:migrate --trace
(in /home/redmine/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
Migrating redmine_embedded_video (Redmine Embedded Video)...
Migrating redmine_telegram_common (Redmine Telegram Common plugin)...
== 1 CreateTelegramCommonAccounts: migrating ==================================
-- create_table(:telegram_common_accounts)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Can't create table 'redmine_production.#sql-32d_8d6' (errno: 150): ALTER TABLE `telegram_common_accounts` ADD CONSTRAINT `fk_rails_465d67b245`
FOREIGN KEY (`user_id`)
  REFERENCES `users` (`id`)
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:776:in `add_foreign_key'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:231:in `block in create_table'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:230:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:230:in `create_table'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:474:in `create_table'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/home/redmine/redmine/plugins/redmine_telegram_common/db/migrate/001_create_telegram_common_accounts.rb:3:in `change'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:608:in `exec_migration'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:453:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:466:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:466:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Can't create table 'redmine_production.#sql-32d_8d6' (errno: 150): ALTER TABLE `telegram_common_accounts` ADD CONSTRAINT `fk_rails_465d67b245`
FOREIGN KEY (`user_id`)
  REFERENCES `users` (`id`)
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:776:in `add_foreign_key'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:231:in `block in create_table'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:230:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:230:in `create_table'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:474:in `create_table'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/home/redmine/redmine/plugins/redmine_telegram_common/db/migrate/001_create_telegram_common_accounts.rb:3:in `change'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:608:in `exec_migration'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:453:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:466:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:466:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
Mysql2::Error: Can't create table 'redmine_production.#sql-32d_8d6' (errno: 150)
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `_query'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:120:in `block in query'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `handle_interrupt'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.8/lib/mysql2/client.rb:119:in `query'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:776:in `add_foreign_key'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:231:in `block in create_table'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:230:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:230:in `create_table'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:474:in `create_table'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/home/redmine/redmine/plugins/redmine_telegram_common/db/migrate/001_create_telegram_common_accounts.rb:3:in `change'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:608:in `exec_migration'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/redmine/redmine/lib/redmine/plugin.rb:453:in `migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/home/redmine/redmine/lib/redmine/plugin.rb:466:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:466:in `migrate'
/home/redmine/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
Tasks: TOP => redmine:plugins:migrate
```
Try to uninstall with

`bundle exec rake redmine:plugins:migrate NAME=redmine_telegram_common VERSION=0`

and install again doesn't work (same error again)

System:

> Environment:
>   Redmine version                3.4.2.stable
>   Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux-gnu]
>   Rails version                  4.2.8
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.8.8
>   Darcs                          2.8.4
>   Mercurial                      2.8.2
>   Cvs                            1.12.13
>   Bazaar                         2.7.0
>   Git                            2.14.1
>   Filesystem                     
> Redmine plugins:
>   redmine_embedded_video         0.0.3.1

**Comment by prodigy7** [comment]
Additional informations:

> SHOW ENGINE INNODB STATUS;

```
------------------------
LATEST FOREIGN KEY ERROR
------------------------
171207 15:15:26 Error in foreign key constraint of table redmine_production/#sql-32d_8d6:

FOREIGN KEY (`user_id`)
 REFERENCES `users` (`id`):
Cannot resolve table name close to:
(`id`)
```

**Comment by olemskoi** [comment]
Do you still need help?
