### ISSUE TITLE
Бот работает, но не отсылает сообщения

### ISSUE THREAD

**Issue by mirkhamidov** [centosadmin/redmine_telegram_common#62]
До этого бот у меня работал, решил обновить, все по инструкции скомпилировал, все привязано

![2018-03-23_13-44-48](https://user-images.githubusercontent.com/2736223/37825335-73d14aa8-2ea0-11e8-98bc-9bf206e68056.png)

Даже в логах что-то есть.

Проблема: не сообщает что есть изменения!

Далее, пробую связать
![2018-03-23_13-47-21](https://user-images.githubusercontent.com/2736223/37825394-b8b6ff64-2ea0-11e8-8308-fbbb3e6e6aac.png)

Вроде не плохо, но, почему то далее сам бот начинает мне с каким то интервалом присылать сообщения справки, так же пробовал обновить информацию о себе, но в ответ ничего нет, только в логах

![2018-03-23_13-51-40](https://user-images.githubusercontent.com/2736223/37825561-567ebe58-2ea1-11e8-8c48-fc2b782aec1d.png)

Логи идут

![2018-03-23_13-52-14](https://user-images.githubusercontent.com/2736223/37825587-6ef05514-2ea1-11e8-8a80-6e964cfc0d1a.png)

**==> intouch/telegram-live-sender.log <==**
```
D, [2018-03-23T13:46:50.532352 #1176] DEBUG -- : user: #<User id: 5, login: "miroff", hashed_password: "7ba***", firstname: "*", lastname: "*", admin: true, status: 1, last_login_on: "2018-03-21 07:55:37", language: "ru", auth_source_id: nil, created_on: "2012-03-31 09:52:23", updated_on: "2017-02-16 14:50:04", type: "User", identity_url: nil, mail_notification: "all", salt: "4*", phone: nil, address: nil, skype: nil, birthday: nil, job_title: nil, company: nil, middlename: nil, gender: nil, twitter: nil, facebook: nil, linkedin: nil, background: nil, appearance_date: nil, department_id: nil, must_change_passwd: false, passwd_changed_on: nil>
D, [2018-03-23T13:46:50.534280 #1176] DEBUG -- : telegram_account: #<TelegramCommon::Account id: 1, telegram_id: 25**, username: "miroff", first_name: "Jasur", last_name: "Mirkhamidov", user_id: 5, active: true, token: "90*", connect_trials_count: 1, blocked_at: nil, last_try_at: nil>
D, [2018-03-23T13:46:50.535309 #1176] DEBUG -- : roles_in_issue: ["assigned_to", "author"]
D, [2018-03-23T13:46:50.535855 #1176] DEBUG -- : Исполнителю, Автору
`Reader: тест`
Назначена: Джасур Мирхамидов
Приоритет: Нормальный
Статус: Новый
https://**/issues/1212
D, [2018-03-23T13:46:50.536686 #1176] DEBUG -- : "764c***"
D, [2018-03-23T13:46:50.536857 #1176] DEBUG -- : FINISH for issue_id 1212
```

**==> intouch/telegram-message-sender-errors.log <==**
```
I, [2018-03-23T13:46:50.605080 #1176]  INFO -- : MESSAGE: Исполнителю, Автору
`Reader: тест`
Назначена: Джасур Мирхамидов
Приоритет: Нормальный
Статус: Новый
https://**/issues/1212
E, [2018-03-23T13:46:50.606869 #1176] ERROR -- : Telegram::Bot::Exceptions::ResponseError: Telegram API has returned the error. (ok: "false", error_code: "404", description: "Not Found")
D, [2018-03-23T13:46:50.607368 #1176] DEBUG -- : #<TelegramCommon::Account id: 1, telegram_id: 25**, username: "miroff", first_name: "Jasur", last_name: "Mirkhamidov", user_id: 5, active: true, token: "90a6**", connect_trials_count: 1, blocked_at: nil, last_try_at: nil>
I, [2018-03-23T13:46:50.609001 #1176]  INFO -- : MESSAGE: `Reader: тест`
Назначена: Джасур Мирхамидов
Приоритет: Нормальный
Статус: Новый
https://**/issues/1212
E, [2018-03-23T13:46:50.610376 #1176] ERROR -- : Telegram::Bot::Exceptions::ResponseError: Telegram API has returned the error. (ok: "false", error_code: "404", description: "Not Found")
D, [2018-03-23T13:46:50.610741 #1176] DEBUG -- : #<TelegramGroupChat id: 3, tid: 1968**, title: "****">
```

Даже не знаю как еще описать проблему (

**Comment by funk-yourself** [comment]
Добрый день! Напишите, пожалуйста, версии redmine_telegram_common и redmine_intouch (и других наших телеграм-плагинов, если установлены).
Похоже, что установлена старая версия redmine_intouch, она несовместима с последней версией redmine_telegram_common.

**Comment by mirkhamidov** [comment]
![2018-03-23_14-31-05](https://user-images.githubusercontent.com/2736223/37827046-e413490a-2ea6-11e8-9d71-3cec370d4f66.png)

**Comment by funk-yourself** [comment]
Используются webhooks или getUpdates? После обновления переинициализировали бота?

**Comment by mirkhamidov** [comment]
webhooks
Да

Кажется проблема устранилась после перезагрузки, Но, в группы не приходят сообщения. Какие требования по группе?

**Comment by funk-yourself** [comment]
Выполняли команду rake telegram_common:migrate_to_single_bot? Если да, то теперь и в redmine_intouch, и в redmine_chat_telegram используется бот из redmine_chat_telegram. Его нужно добавить в чаты, где был бот от intouch вместо старого бота.

**Comment by mirkhamidov** [comment]
Нет, не выполнял, сейчас сделаю.
Так у меня сам бот то не поменялся

**Comment by mirkhamidov** [comment]
получил ошибку 
```
$ rake telegram_common:migrate_to_single_bot
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'redmine_dev.settings' doesn't exist: SHOW FULL FIELDS FROM `settings`
/home/peacedata/redmine/app/models/setting.rb:313:in `find_or_default'
/home/peacedata/redmine/app/models/setting.rb:110:in `[]'
/home/peacedata/redmine/app/models/setting.rb:271:in `plugin_a_common_libs'
/home/peacedata/redmine/plugins/a_common_libs/init.rb:139:in `block in <top (required)>'
/home/peacedata/redmine/config/environment.rb:14:in `<top (required)>'
/home/peacedata/redmine/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/home/peacedata/redmine/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/home/peacedata/redmine/lib/tasks/redmine.rake:194:in `each'
/home/peacedata/redmine/lib/tasks/redmine.rake:194:in `<top (required)>'
/home/peacedata/redmine/Rakefile:7:in `<top (required)>'
Mysql2::Error: Table 'redmine_dev.settings' doesn't exist
/home/peacedata/redmine/app/models/setting.rb:313:in `find_or_default'
/home/peacedata/redmine/app/models/setting.rb:110:in `[]'
/home/peacedata/redmine/app/models/setting.rb:271:in `plugin_a_common_libs'
/home/peacedata/redmine/plugins/a_common_libs/init.rb:139:in `block in <top (required)>'
/home/peacedata/redmine/config/environment.rb:14:in `<top (required)>'
/home/peacedata/redmine/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/home/peacedata/redmine/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/home/peacedata/redmine/lib/tasks/redmine.rake:194:in `each'
/home/peacedata/redmine/lib/tasks/redmine.rake:194:in `<top (required)>'
/home/peacedata/redmine/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by mirkhamidov** [comment]
У меня postgresql стоит

**Comment by funk-yourself** [comment]
`rake telegram_common:migrate_to_single_bot RAILS_ENV=production` в продакшн-окружении

**Comment by mirkhamidov** [comment]
Супер, вроде все заработало.
Еще момент, нельзя ли как то поменять (самостоятельно,  custom) сообщения? Хотелось бы видеть в сообщение, что конкретно изменилось, например, если добавил комментарий, то увидеть его

**Comment by funk-yourself** [comment]
>Еще момент, нельзя ли как то поменять (самостоятельно, custom) сообщения? Хотелось бы видеть в сообщение, что конкретно изменилось, например, если добавил комментарий, то увидеть его

Пока что такой возможности нет. В будущем возможно что-нибудь придумаем.
