### ISSUE TITLE
LoadError: No such file to load -- telegram_accouts_refresh_worker

### ISSUE THREAD

**Issue by ananasn** [centosadmin/redmine_telegram_common#80]
При выполнении установки  `bundle exec rake redmine:plugins:migrate RAILS_ENV=production ` вылезает вот такая ошибка. С чем это может быть связано?

```
rake aborted!
LoadError: No such file to load -- telegram_accouts_refresh_worker
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `each'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `block in eager_load!'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `each'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `eager_load!'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:346:in `eager_load!'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `each'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/home/redmine/redmine-3.4.6/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine-3.4.6/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine-3.4.6/lib/tasks/redmine.rake:194:in `block in <top (required)>'
/home/redmine/redmine-3.4.6/lib/tasks/redmine.rake:194:in `each'
/home/redmine/redmine-3.4.6/lib/tasks/redmine.rake:194:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `each'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:658:in `run_tasks_blocks'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/application.rb:452:in `run_tasks_blocks'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:453:in `load_tasks'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/var/lib/gems/2.5.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/home/redmine/redmine-3.4.6/Rakefile:7:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:29:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:29:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:703:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:104:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:103:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:82:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
/usr/bin/rake:27:in `<main>'
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
Redmine 2018-06-10 v3.4.6
Ubuntu 18.04

**Comment by ph223** [comment]
Hello! Same issue
ruby 2.5.1p57 & Redmine 3.4.6 @debian 9

**Comment by funk-yourself** [comment]
Hello! Which revision (commit hash) of plugin do you have?

**Comment by ph223** [comment]
Vladislav,
indeed, there was a mistake in filename, but it shouldn't affect the error. 
Now its on commit 2e1fd10d6f01706d7e951fd6c6d4e56182fa25ee with same error:

$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
Migrating redmine_telegram_common (Redmine Telegram Common plugin)...

and thereafter with passenger:
Error details:

No such file to load -- telegram_accounts_refresh_worker (LoadError)
  /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
  /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
<...etc>

**Comment by olemskoi** [comment]
Please send output of
ls -laF plugins

**Comment by ph223** [comment]
$ ls -laF plugins 
total 16
drwxr-xr-x  3 ruby ruby 4096 Jun 30 15:39 ./
drwxr-xr-x 19 ruby ruby 4096 Jun 30 16:06 ../
-rwxr-xr-x  1 ruby ruby   31 Jun 10 09:36 README*
drwxr-xr-x  8 ruby ruby 4096 Jun 30 15:39 redmine_telegram_common/

**Comment by ananasn** [comment]
Even after the updates, you release it spits out the same error :pensive:
I am on commit 2e1fd10 as well.

**Comment by funk-yourself** [comment]
Do you have redmine_sidekiq installed? It may resolve this error.

**Comment by ph223** [comment]
Vladislav, redmine_sidekiq fixed the problem. Thank you!
I've created the pull request eb893c20248e02b5fcbd6fafd6a0d6d057632844 to make the requirements in readme more visible.

**Comment by olemskoi** [comment]
ananasn, does redmine_sidekiq's installation fix problem?

**Comment by ananasn** [comment]
olemskoi , yeah, it seems to work!
